test: added ENVIRON_TAG for on push to branch

diff --git a/.github/workflows/build_push_and_restart_cas.yml b/.github/workflows/build_push_and_restart_cas.yml
--- a/.github/workflows/build_push_and_restart_cas.yml
+++ b/.github/workflows/build_push_and_restart_cas.yml
@@ -98,17 +98,36 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Stop running tasks
+      - name: Set Variables  ## As per workflow_dispatch  environment input above set based on branch 
+        id: set-vars
         run: |
+          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
+            echo "::set-output name=ENVIRON_TAG::prod"
+          elif [[ "${{github.base_ref}}" == "release-candidate" || "${{github.ref}}" == "refs/heads/release-candidate" ]]; then
+            echo "::set-output name=ENVIRON_TAG::tnet"
+          else
+            echo "::set-output name=ENVIRON_TAG::dev"
+          fi
+
+      - name: Stop running tasks
+        env:
+          ENV_TAG: ${{ steps.set-vars.outputs.ENVIRON_TAG }}
+        run: |
+          echo "ENVIRON_TAG: ${{steps.set-vars.outputs.ENVIRON_TAG}}"
+          if [[ "${{steps.set-vars.outputs.ENVIRON_TAG}}" != "none" ]]; then
+            ec=$(aws ecs list-tasks --cluster "ceramic-${{ steps.set-vars.outputs.ENVIRON_TAG }}-cas" --service "ceramic-${{ steps.set-vars.outputs.ENVIRON_TAG }}-cas-api" 2>&1 | grep " error " | wc -l)
+            TASK_IDS=$(aws ecs list-tasks --cluster "ceramic-${{ steps.set-vars.outputs.ENVIRON_TAG }}-cas" --service "ceramic-${{ steps.set-vars.outputs.ENVIRON_TAG }}-cas-api" | grep "task/" | sed -E 's/.*task\/(.*\/[a-zA-Z0-9]*)(.*)/\1/' | tr '\n' ' ')
+          else
             ec=$(aws ecs list-tasks --cluster "${{ matrix.cluster }}" --service "${{ matrix.service }}" 2>&1 | grep " error " | wc -l)
             TASK_IDS=$(aws ecs list-tasks --cluster "${{ matrix.cluster }}" --service "${{ matrix.service }}" | grep "task/" | sed -E 's/.*task\/(.*\/[a-zA-Z0-9]*)(.*)/\1/' | tr '\n' ' ')
-            echo "Task Ids: ${TASK_IDS}"
-            if [[ $ec -ne 0 ]]; then
-               echo "ERROR: $ec error(s) occurred,  aborting ....." && exit $ec
+          fi
+          echo "Task Ids: ${TASK_IDS}"
+          if [[ $ec -ne 0 ]]; then
+             echo "ERROR: $ec error(s) occurred,  aborting ....." && exit $ec
+          fi
+          for t in ${TASK_IDS[@]}; do
+            if [[ $t ]]; then
+              echo "Stopping task $t"
+              aws ecs stop-task --cluster ${{ matrix.cluster }} --task $t
             fi
-            for t in ${TASK_IDS[@]}; do
-              if [[ $t ]]; then
-                echo "Stopping task $t"
-                aws ecs stop-task --cluster ${{ matrix.cluster }} --task $t
-              fi
-            done
+          done
